use_frameworks!

platform :ios, '9.0'

target 'YHome_Example' do
  pod 'YHome', :path => '../'

  target 'YHome_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
